### ISSUE TITLE
Getting Error during the run docker command

### ISSUE THREAD

**Issue by AashishChughHome** [frodenas/grafana_exporter#3]
I am getting below error after run following command, i don't know how to pass a flag, can you provide a example here.

command - **docker run -p 9261:9261 frodenas/grafana-exporter**

Error - time="2018-11-13T11:52:46Z" level=error msg="Flag `grafana.uri` is required" source="grafana_exporter.go:96"

**Comment by frodenas** [comment]
You just need to pass the args after the docker image: `docker run -p 9261:9261 frodenas/grafana-exporter <flags>`. Flags are documented [here](https://github.com/frodenas/grafana_exporter#flags).
